<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Adds EVERY column from billpTMP.csv (238 total) onto the products
     * table, prefixed rc_ ("raw column") so none of them can ever collide
     * with product_name / product_code / product_brand / price or any
     * other column you already have. Stored as nullable TEXT since the
     * source data is a mix of numbers, blanks, and free text.
     */
    public function up(): void
    {
        Schema::table('products', function (Blueprint $table) {
            $table->text('rc_fshow')->nullable();
            $table->text('rc_fshow1')->nullable();
            $table->text('rc_fshow2')->nullable();
            $table->text('rc_fshow3')->nullable();
            $table->text('rc_fshow4')->nullable();
            $table->text('rc_fshow5')->nullable();
            $table->text('rc_fshow6')->nullable();
            $table->text('rc_fshow7')->nullable();
            $table->text('rc_fshow8')->nullable();
            $table->text('rc_fshow9')->nullable();
            $table->text('rc_termper')->nullable();
            $table->text('rc_warrmo')->nullable();
            $table->text('rc_statrem')->nullable();
            $table->text('rc_p_vendorc')->nullable();
            $table->text('rc_prod_brc')->nullable();
            $table->text('rc_prod_cn')->nullable();
            $table->text('rc_prod_c')->nullable();
            $table->text('rc_prod_cr')->nullable();
            $table->text('rc_sprd')->nullable();
            $table->text('rc_act')->nullable();
            $table->text('rc_status')->nullable();
            $table->text('rc_pp')->nullable();
            $table->text('rc_feat_i')->nullable();
            $table->text('rc_inv_lvl')->nullable();
            $table->text('rc_pi_imp_lv')->nullable();
            $table->text('rc_pc_ii')->nullable();
            $table->text('rc_prod_r')->nullable();
            $table->text('rc_prn_ctrl')->nullable();
            $table->text('rc_prod_chl')->nullable();
            $table->text('rc_prod_brand')->nullable();
            $table->text('rc_prodbrandn')->nullable();
            $table->text('rc_prod_n')->nullable();
            $table->text('rc_prod_d')->nullable();
            $table->text('rc_free')->nullable();
            $table->text('rc_bi_purch')->nullable();
            $table->text('rc_serial')->nullable();
            $table->text('rc_bundled')->nullable();
            $table->text('rc_sku1')->nullable();
            $table->text('rc_sku1q')->nullable();
            $table->text('rc_sku1c')->nullable();
            $table->text('rc_sku2')->nullable();
            $table->text('rc_sku2q')->nullable();
            $table->text('rc_sku2c')->nullable();
            $table->text('rc_sku3')->nullable();
            $table->text('rc_sku3q')->nullable();
            $table->text('rc_sku3c')->nullable();
            $table->text('rc_sku4')->nullable();
            $table->text('rc_sku4q')->nullable();
            $table->text('rc_sku4c')->nullable();
            $table->text('rc_sku5')->nullable();
            $table->text('rc_sku5q')->nullable();
            $table->text('rc_sku5c')->nullable();
            $table->text('rc_sku6')->nullable();
            $table->text('rc_sku6q')->nullable();
            $table->text('rc_sku6c')->nullable();
            $table->text('rc_pc_fc')->nullable();
            $table->text('rc_pc_nc')->nullable();
            $table->text('rc_pc_c')->nullable();
            $table->text('rc_pc_pf')->nullable();
            $table->text('rc_pc_lp')->nullable();
            $table->text('rc_pc_pa')->nullable();
            $table->text('rc_pc_lc')->nullable();
            $table->text('rc_pc_pg')->nullable();
            $table->text('rc_pc_ph')->nullable();
            $table->text('rc_pc_pb')->nullable();
            $table->text('rc_pc_pd')->nullable();
            $table->text('rc_pc_pc')->nullable();
            $table->text('rc_pc_pn')->nullable();
            $table->text('rc_sly_q')->nullable();
            $table->text('rc_sly_a')->nullable();
            $table->text('rc_ly_cg')->nullable();
            $table->text('rc_pi_byear')->nullable();
            $table->text('rc_pi_yqs')->nullable();
            $table->text('rc_pc_ysa')->nullable();
            $table->text('rc_pi_mqs')->nullable();
            $table->text('rc_pc_msa')->nullable();
            $table->text('rc_pc_ycs')->nullable();
            $table->text('rc_pc_mcs')->nullable();
            $table->text('rc_pi_yqa')->nullable();
            $table->text('rc_pi_boh')->nullable();
            $table->text('rc_pi_tq')->nullable();
            $table->text('rc_pi_uq')->nullable();
            $table->text('rc_extra')->nullable();
            $table->text('rc_nwf')->nullable();
            $table->text('rc_nwfr')->nullable();
            $table->text('rc_ly_purc')->nullable();
            $table->text('rc_pi_yqr')->nullable();
            $table->text('rc_prod_incr')->nullable();
            $table->text('rc_prod_uinc')->nullable();
            $table->text('rc_term')->nullable();
            $table->text('rc_pterm')->nullable();
            $table->text('rc_sr_amt')->nullable();
            $table->text('rc_pr1_r')->nullable();
            $table->text('rc_pr1_a')->nullable();
            $table->text('rc_pr2_r')->nullable();
            $table->text('rc_pr2_a')->nullable();
            $table->text('rc_pr3_r')->nullable();
            $table->text('rc_pr3_a')->nullable();
            $table->text('rc_pr4_r')->nullable();
            $table->text('rc_pr4_a')->nullable();
            $table->text('rc_cate_n')->nullable();
            $table->text('rc_cs1')->nullable();
            $table->text('rc_cs2')->nullable();
            $table->text('rc_cs3')->nullable();
            $table->text('rc_cs4')->nullable();
            $table->text('rc_tag_sel')->nullable();
            $table->text('rc_tag_sel1')->nullable();
            $table->text('rc_tag_sel2')->nullable();
            $table->text('rc_tag_sel3')->nullable();
            $table->text('rc_tag_sel4')->nullable();
            $table->text('rc_prod_ra1c')->nullable();
            $table->text('rc_prod_ra1')->nullable();
            $table->text('rc_prod_ra2c')->nullable();
            $table->text('rc_prod_ra2')->nullable();
            $table->text('rc_prod_ra3c')->nullable();
            $table->text('rc_prod_ra3')->nullable();
            $table->text('rc_prod_ra4c')->nullable();
            $table->text('rc_prod_ra4')->nullable();
            $table->text('rc_img_ctrl')->nullable();
            $table->text('rc_prod_pre')->nullable();
            $table->text('rc_theme_m')->nullable();
            $table->text('rc_theme_1')->nullable();
            $table->text('rc_feat_m')->nullable();
            $table->text('rc_feat_1')->nullable();
            $table->text('rc_feat_1n')->nullable();
            $table->text('rc_feat_1v')->nullable();
            $table->text('rc_feat_2')->nullable();
            $table->text('rc_feat_2n')->nullable();
            $table->text('rc_feat_2v')->nullable();
            $table->text('rc_feat_3')->nullable();
            $table->text('rc_feat_3n')->nullable();
            $table->text('rc_feat_3v')->nullable();
            $table->text('rc_feat_4')->nullable();
            $table->text('rc_feat_4n')->nullable();
            $table->text('rc_feat_4v')->nullable();
            $table->text('rc_feat_5')->nullable();
            $table->text('rc_feat_6')->nullable();
            $table->text('rc_feat_7')->nullable();
            $table->text('rc_feat_8')->nullable();
            $table->text('rc_feat_9')->nullable();
            $table->text('rc_feat_10')->nullable();
            $table->text('rc_feat_11')->nullable();
            $table->text('rc_feat_12')->nullable();
            $table->text('rc_feat_13')->nullable();
            $table->text('rc_feat_14')->nullable();
            $table->text('rc_feat_15')->nullable();
            $table->text('rc_coni_m')->nullable();
            $table->text('rc_coni_1')->nullable();
            $table->text('rc_coni_2')->nullable();
            $table->text('rc_coni_3')->nullable();
            $table->text('rc_freec1')->nullable();
            $table->text('rc_free_m')->nullable();
            $table->text('rc_freec2')->nullable();
            $table->text('rc_free_1')->nullable();
            $table->text('rc_freec3')->nullable();
            $table->text('rc_free_2')->nullable();
            $table->text('rc_freec4')->nullable();
            $table->text('rc_free_3')->nullable();
            $table->text('rc_t_color')->nullable();
            $table->text('rc_cap_m')->nullable();
            $table->text('rc_cap_1')->nullable();
            $table->text('rc_cap_2')->nullable();
            $table->text('rc_cap_3')->nullable();
            $table->text('rc_cap_4')->nullable();
            $table->text('rc_pc_pfl')->nullable();
            $table->text('rc_pc_rp')->nullable();
            $table->text('rc_pc_ppa2lp')->nullable();
            $table->text('rc_pc_ppa2wb')->nullable();
            $table->text('rc_pc_wb')->nullable();
            $table->text('rc_pc_ppa2lc')->nullable();
            $table->text('rc_pc_ppa2pg')->nullable();
            $table->text('rc_pc_ppa2ph')->nullable();
            $table->text('rc_pc_ppa2pb')->nullable();
            $table->text('rc_pc_ppa2pd')->nullable();
            $table->text('rc_pc_ppa2pc')->nullable();
            $table->text('rc_prod_nt')->nullable();
            $table->text('rc_fpo')->nullable();
            $table->text('rc_tpo')->nullable();
            $table->text('rc_tpo1')->nullable();
            $table->text('rc_tpo2')->nullable();
            $table->text('rc_pi_rl')->nullable();
            $table->text('rc_pi_rq')->nullable();
            $table->text('rc_lpp_amt')->nullable();
            $table->text('rc_lpp_ref')->nullable();
            $table->text('rc_prn_ctrla')->nullable();
            $table->text('rc_attn')->nullable();
            $table->text('rc_p_freec1')->nullable();
            $table->text('rc_p_freec2')->nullable();
            $table->text('rc_p_freec3')->nullable();
            $table->text('rc_p_freec4')->nullable();
            $table->text('rc_p_freec5')->nullable();
            $table->text('rc_p_freeq1')->nullable();
            $table->text('rc_p_freeq2')->nullable();
            $table->text('rc_p_freeq3')->nullable();
            $table->text('rc_p_freeq4')->nullable();
            $table->text('rc_p_freeq5')->nullable();
            $table->text('rc_s_freeq1')->nullable();
            $table->text('rc_s_freeq2')->nullable();
            $table->text('rc_s_freeq3')->nullable();
            $table->text('rc_s_freeq4')->nullable();
            $table->text('rc_s_freeq5')->nullable();
            $table->text('rc_freec5')->nullable();
            $table->text('rc_vatr')->nullable();
            $table->text('rc_plfob')->nullable();
            $table->text('rc_v_item_d')->nullable();
            $table->text('rc_pc_lsrp')->nullable();
            $table->text('rc_pc_plsrp')->nullable();
            $table->text('rc_pc_wc')->nullable();
            $table->text('rc_pc_ppa2wc')->nullable();
            $table->text('rc_img_grp')->nullable();
            $table->text('rc_pi_fib')->nullable();
            $table->text('rc_pc_ecwv')->nullable();
            $table->text('rc_pc_cur_c')->nullable();
            $table->text('rc_prod_ct')->nullable();
            $table->text('rc_prod_tf')->nullable();
            $table->text('rc_pc_wa')->nullable();
            $table->text('rc_pc_ppa2wa')->nullable();
            $table->text('rc_pi_nwt')->nullable();
            $table->text('rc_pi_nvol')->nullable();
            $table->text('rc_pi_measur1')->nullable();
            $table->text('rc_pi_measur2')->nullable();
            $table->text('rc_pi_measur3')->nullable();
            $table->text('rc_pi_freight')->nullable();
            $table->text('rc_gp1')->nullable();
            $table->text('rc_gp2')->nullable();
            $table->text('rc_gp3')->nullable();
            $table->text('rc_tmpp')->nullable();
            $table->text('rc_inv2adj')->nullable();
            $table->text('rc_sr1_dt')->nullable();
            $table->text('rc_sr1a_dt')->nullable();
            $table->text('rc_pr1_dt')->nullable();
            $table->text('rc_pr2_dt')->nullable();
            $table->text('rc_pr3_dt')->nullable();
            $table->text('rc_pr4_dt')->nullable();
            $table->text('rc_pr1a_dt')->nullable();
            $table->text('rc_pr2a_dt')->nullable();
            $table->text('rc_pr3a_dt')->nullable();
            $table->text('rc_pr4a_dt')->nullable();
        });

        // Wide row (238 extra text columns) — DYNAMIC row format lets
        // InnoDB store large values off-page and avoids hitting the
        // ~65,535 byte in-row size limit.
        DB::statement('ALTER TABLE products ROW_FORMAT=DYNAMIC');
    }

    public function down(): void
    {
        Schema::table('products', function (Blueprint $table) {
$columns = [
                'rc_fshow',
                'rc_fshow1',
                'rc_fshow2',
                'rc_fshow3',
                'rc_fshow4',
                'rc_fshow5',
                'rc_fshow6',
                'rc_fshow7',
                'rc_fshow8',
                'rc_fshow9',
                'rc_termper',
                'rc_warrmo',
                'rc_statrem',
                'rc_p_vendorc',
                'rc_prod_brc',
                'rc_prod_cn',
                'rc_prod_c',
                'rc_prod_cr',
                'rc_sprd',
                'rc_act',
                'rc_status',
                'rc_pp',
                'rc_feat_i',
                'rc_inv_lvl',
                'rc_pi_imp_lv',
                'rc_pc_ii',
                'rc_prod_r',
                'rc_prn_ctrl',
                'rc_prod_chl',
                'rc_prod_brand',
                'rc_prodbrandn',
                'rc_prod_n',
                'rc_prod_d',
                'rc_free',
                'rc_bi_purch',
                'rc_serial',
                'rc_bundled',
                'rc_sku1',
                'rc_sku1q',
                'rc_sku1c',
                'rc_sku2',
                'rc_sku2q',
                'rc_sku2c',
                'rc_sku3',
                'rc_sku3q',
                'rc_sku3c',
                'rc_sku4',
                'rc_sku4q',
                'rc_sku4c',
                'rc_sku5',
                'rc_sku5q',
                'rc_sku5c',
                'rc_sku6',
                'rc_sku6q',
                'rc_sku6c',
                'rc_pc_fc',
                'rc_pc_nc',
                'rc_pc_c',
                'rc_pc_pf',
                'rc_pc_lp',
                'rc_pc_pa',
                'rc_pc_lc',
                'rc_pc_pg',
                'rc_pc_ph',
                'rc_pc_pb',
                'rc_pc_pd',
                'rc_pc_pc',
                'rc_pc_pn',
                'rc_sly_q',
                'rc_sly_a',
                'rc_ly_cg',
                'rc_pi_byear',
                'rc_pi_yqs',
                'rc_pc_ysa',
                'rc_pi_mqs',
                'rc_pc_msa',
                'rc_pc_ycs',
                'rc_pc_mcs',
                'rc_pi_yqa',
                'rc_pi_boh',
                'rc_pi_tq',
                'rc_pi_uq',
                'rc_extra',
                'rc_nwf',
                'rc_nwfr',
                'rc_ly_purc',
                'rc_pi_yqr',
                'rc_prod_incr',
                'rc_prod_uinc',
                'rc_term',
                'rc_pterm',
                'rc_sr_amt',
                'rc_pr1_r',
                'rc_pr1_a',
                'rc_pr2_r',
                'rc_pr2_a',
                'rc_pr3_r',
                'rc_pr3_a',
                'rc_pr4_r',
                'rc_pr4_a',
                'rc_cate_n',
                'rc_cs1',
                'rc_cs2',
                'rc_cs3',
                'rc_cs4',
                'rc_tag_sel',
                'rc_tag_sel1',
                'rc_tag_sel2',
                'rc_tag_sel3',
                'rc_tag_sel4',
                'rc_prod_ra1c',
                'rc_prod_ra1',
                'rc_prod_ra2c',
                'rc_prod_ra2',
                'rc_prod_ra3c',
                'rc_prod_ra3',
                'rc_prod_ra4c',
                'rc_prod_ra4',
                'rc_img_ctrl',
                'rc_prod_pre',
                'rc_theme_m',
                'rc_theme_1',
                'rc_feat_m',
                'rc_feat_1',
                'rc_feat_1n',
                'rc_feat_1v',
                'rc_feat_2',
                'rc_feat_2n',
                'rc_feat_2v',
                'rc_feat_3',
                'rc_feat_3n',
                'rc_feat_3v',
                'rc_feat_4',
                'rc_feat_4n',
                'rc_feat_4v',
                'rc_feat_5',
                'rc_feat_6',
                'rc_feat_7',
                'rc_feat_8',
                'rc_feat_9',
                'rc_feat_10',
                'rc_feat_11',
                'rc_feat_12',
                'rc_feat_13',
                'rc_feat_14',
                'rc_feat_15',
                'rc_coni_m',
                'rc_coni_1',
                'rc_coni_2',
                'rc_coni_3',
                'rc_freec1',
                'rc_free_m',
                'rc_freec2',
                'rc_free_1',
                'rc_freec3',
                'rc_free_2',
                'rc_freec4',
                'rc_free_3',
                'rc_t_color',
                'rc_cap_m',
                'rc_cap_1',
                'rc_cap_2',
                'rc_cap_3',
                'rc_cap_4',
                'rc_pc_pfl',
                'rc_pc_rp',
                'rc_pc_ppa2lp',
                'rc_pc_ppa2wb',
                'rc_pc_wb',
                'rc_pc_ppa2lc',
                'rc_pc_ppa2pg',
                'rc_pc_ppa2ph',
                'rc_pc_ppa2pb',
                'rc_pc_ppa2pd',
                'rc_pc_ppa2pc',
                'rc_prod_nt',
                'rc_fpo',
                'rc_tpo',
                'rc_tpo1',
                'rc_tpo2',
                'rc_pi_rl',
                'rc_pi_rq',
                'rc_lpp_amt',
                'rc_lpp_ref',
                'rc_prn_ctrla',
                'rc_attn',
                'rc_p_freec1',
                'rc_p_freec2',
                'rc_p_freec3',
                'rc_p_freec4',
                'rc_p_freec5',
                'rc_p_freeq1',
                'rc_p_freeq2',
                'rc_p_freeq3',
                'rc_p_freeq4',
                'rc_p_freeq5',
                'rc_s_freeq1',
                'rc_s_freeq2',
                'rc_s_freeq3',
                'rc_s_freeq4',
                'rc_s_freeq5',
                'rc_freec5',
                'rc_vatr',
                'rc_plfob',
                'rc_v_item_d',
                'rc_pc_lsrp',
                'rc_pc_plsrp',
                'rc_pc_wc',
                'rc_pc_ppa2wc',
                'rc_img_grp',
                'rc_pi_fib',
                'rc_pc_ecwv',
                'rc_pc_cur_c',
                'rc_prod_ct',
                'rc_prod_tf',
                'rc_pc_wa',
                'rc_pc_ppa2wa',
                'rc_pi_nwt',
                'rc_pi_nvol',
                'rc_pi_measur1',
                'rc_pi_measur2',
                'rc_pi_measur3',
                'rc_pi_freight',
                'rc_gp1',
                'rc_gp2',
                'rc_gp3',
                'rc_tmpp',
                'rc_inv2adj',
                'rc_sr1_dt',
                'rc_sr1a_dt',
                'rc_pr1_dt',
                'rc_pr2_dt',
                'rc_pr3_dt',
                'rc_pr4_dt',
                'rc_pr1a_dt',
                'rc_pr2a_dt',
                'rc_pr3a_dt',
                'rc_pr4a_dt'
            ];
            $table->dropColumn($columns);
        });
    }
};